# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0003_blog_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='username',
            new_name='email',
        ),
    ]
