# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0004_auto_20170827_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='email',
            new_name='email_address',
        ),
    ]
