# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0005_auto_20170827_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='email_address',
            new_name='username',
        ),
    ]
