# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0006_auto_20170827_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='det',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
